# Generated by Django 3.1.7 on 2021-03-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutionblog', '0002_auto_20210319_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='platform',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='solutionblog.platform'),
        ),
    ]
