# Generated by Django 3.1.7 on 2021-03-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutionblog', '0005_auto_20210319_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='platform',
        ),
    ]
