# Generated by Django 3.1.7 on 2021-03-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutionblog', '0006_remove_question_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='solutionblog.platform'),
        ),
    ]
