# Generated by Django 3.1.7 on 2021-03-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutionblog', '0012_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(to='solutionblog.Topic'),
        ),
    ]
