# Generated by Django 3.1.7 on 2021-03-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutionblog', '0014_auto_20210326_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='questions', to='solutionblog.Topic'),
        ),
    ]
